### ISSUE TITLE
articlepageエラー

### ISSUE THREAD

**Issue by IwaseMio** [shinonome-inc/mobile_Mio_azuma_basic_flutter#26]
E/flutter ( 7297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7297): #0      InstanceManagerHostApi.clear (package:webview_flutter_android/src/android_webview.g.dart:251:7)
E/flutter ( 7297): <asynchronous suspension>
E/flutter ( 7297): 
E/flutter ( 7297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7297): #0      WebStorageHostApi.create (package:webview_flutter_android/src/android_webview.g.dart:2705:7)
E/flutter ( 7297): <asynchronous suspension>
E/flutter ( 7297): 
E/flutter ( 7297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7297): #0      WebViewHostApi.create (package:webview_flutter_android/src/android_webview.g.dart:500:7)
E/flutter ( 7297): <asynchronous suspension>
E/flutter ( 7297): 
E/flutter ( 7297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7297): #0      WebSettingsHostApi.create (package:webview_flutter_android/src/android_webview.g.dart:1239:7)
E/flutter ( 7297): <asynchronous suspension>
E/flutter ( 7297): 
E/flutter ( 7297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7297): #0      WebSettingsHostApi.setDomStorageEnabled (package:webview_flutter_android/src/android_webview.g.dart:1262:7)
E/flutter ( 7297): <asynchronous suspension>
E/flutter ( 7297): 
E/flutter ( 7297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7297): #0      WebSettingsHostApi.setJavaScriptCanOpenWindowsAutomatically (package:webview_flutter_android/src/android_webview.g.dart:1286:7)
E/flutter ( 7297): <asynchronous suspension>
E/flutter ( 7297): 
E/flutter ( 7297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7297): #0      WebSettingsHostApi.setSupportMultipleWindows (package:webview_flutter_android/src/android_webview.g.dart:1310:7)
E/flutter ( 7297): <asynchronous suspension>
E/flutter ( 7297): 
E/flutter ( 7297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7297): #0      WebSettingsHostApi.setLoadWithOverviewMode (package:webview_flutter_android/src/android_webview.g.dart:1428:7)
E/flutter ( 7297): <asynchronous suspension>
E/flutter ( 7297): 
E/flutter ( 7297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7297): #0      WebSettingsHostApi.setUseWideViewPort (package:webview_flutter_android/src/android_webview.g.dart:1451:7)
E/flutter ( 7297): <asynchronous suspension>
E/flutter ( 7297): 
E/flutter ( 7297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7297): #0      WebSettingsHostApi.setDisplayZoomControls (package:webview_flutter_android/src/android_webview.g.dart:1475:7)
E/flutter ( 7297): <asynchronous suspension>
E/flutter ( 7297): 
E/flutter ( 7297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7297): #0      WebSettingsHostApi.setBuiltInZoomControls (package:webview_flutter_android/src/android_webview.g.dart:1499:7)
E/flutter ( 7297): <asynchronous suspension>
E/flutter ( 7297): 
E/flutter ( 7297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7297): #0      WebChromeClientHostApi.create (package:webview_flutter_android/src/android_webview.g.dart:2144:7)
E/flutter ( 7297): <asynchronous suspension>
E/flutter ( 7297): 
E/flutter ( 7297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7297): #0      WebViewHostApi.setWebChromeClient (package:webview_flutter_android/src/android_webview.g.dart:1107:7)
E/flutter ( 7297): <asynchronous suspension>
E/flutter ( 7297): 
E/flutter ( 7297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7297): #0      WebViewHostApi.loadUrl (package:webview_flutter_android/src/android_webview.g.dart:585:7)
E/flutter ( 7297): <asynchronous suspension>
E/flutter ( 7297): 
D/EGL_emulation( 7297): app_time_stats: avg=184.96ms min=66.98ms max=474.48ms count=7
E/flutter ( 7297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: plugins.flutter.io/webview
E/flutter ( 7297): 	at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:506)
E/flutter ( 7297): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:193)
E/flutter ( 7297): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:128)
E/flutter ( 7297): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
E/flutter ( 7297): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/flutter ( 7297): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter ( 7297): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter ( 7297): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 7297): 	at android.os.Handler.handleCallback(Handler.java:958)
E/flutter ( 7297): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 7297): 	at android.os.Looper.loopOnce(Looper.java:205)
E/flutter ( 7297): 	at android.os.Looper.loop(Looper.java:294)
E/flutter ( 7297): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/flutter ( 7297): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 7297): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/flutter ( 7297): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/flutter ( 7297): , null, null)
E/flutter ( 7297): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
E/flutter ( 7297): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:322:18)
E/flutter ( 7297): <asynchronous suspension>
E/flutter ( 7297): #2      SurfaceAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1017:30)
E/flutter ( 7297): <asynchronous suspension>
E/flutter ( 7297): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:804:5)
E/flutter ( 7297): <asynchronous suspension>
E/flutter ( 7297):

**Comment by KobayashiYoh** [comment]
```
E/flutter ( 7297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7297): #0 InstanceManagerHostApi.clear (package:webview_flutter_android/src/android_webview.g.dart:251:7)
E/flutter ( 7297):
E/flutter ( 7297):
E/flutter ( 7297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7297): #0 WebStorageHostApi.create (package:webview_flutter_android/src/android_webview.g.dart:2705:7)
E/flutter ( 7297):
E/flutter ( 7297):
E/flutter ( 7297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7297): #0 WebViewHostApi.create (package:webview_flutter_android/src/android_webview.g.dart:500:7)
E/flutter ( 7297):
E/flutter ( 7297):
E/flutter ( 7297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7297): #0 WebSettingsHostApi.create (package:webview_flutter_android/src/android_webview.g.dart:1239:7)
E/flutter ( 7297):
E/flutter ( 7297):
E/flutter ( 7297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7297): #0 WebSettingsHostApi.setDomStorageEnabled (package:webview_flutter_android/src/android_webview.g.dart:1262:7)
E/flutter ( 7297):
E/flutter ( 7297):
E/flutter ( 7297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7297): #0 WebSettingsHostApi.setJavaScriptCanOpenWindowsAutomatically (package:webview_flutter_android/src/android_webview.g.dart:1286:7)
E/flutter ( 7297):
E/flutter ( 7297):
E/flutter ( 7297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7297): #0 WebSettingsHostApi.setSupportMultipleWindows (package:webview_flutter_android/src/android_webview.g.dart:1310:7)
E/flutter ( 7297):
E/flutter ( 7297):
E/flutter ( 7297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7297): #0 WebSettingsHostApi.setLoadWithOverviewMode (package:webview_flutter_android/src/android_webview.g.dart:1428:7)
E/flutter ( 7297):
E/flutter ( 7297):
E/flutter ( 7297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7297): #0 WebSettingsHostApi.setUseWideViewPort (package:webview_flutter_android/src/android_webview.g.dart:1451:7)
E/flutter ( 7297):
E/flutter ( 7297):
E/flutter ( 7297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7297): #0 WebSettingsHostApi.setDisplayZoomControls (package:webview_flutter_android/src/android_webview.g.dart:1475:7)
E/flutter ( 7297):
E/flutter ( 7297):
E/flutter ( 7297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7297): #0 WebSettingsHostApi.setBuiltInZoomControls (package:webview_flutter_android/src/android_webview.g.dart:1499:7)
E/flutter ( 7297):
E/flutter ( 7297):
E/flutter ( 7297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7297): #0 WebChromeClientHostApi.create (package:webview_flutter_android/src/android_webview.g.dart:2144:7)
E/flutter ( 7297):
E/flutter ( 7297):
E/flutter ( 7297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7297): #0 WebViewHostApi.setWebChromeClient (package:webview_flutter_android/src/android_webview.g.dart:1107:7)
E/flutter ( 7297):
E/flutter ( 7297):
E/flutter ( 7297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 7297): #0 WebViewHostApi.loadUrl (package:webview_flutter_android/src/android_webview.g.dart:585:7)
E/flutter ( 7297):
E/flutter ( 7297):
D/EGL_emulation( 7297): app_time_stats: avg=184.96ms min=66.98ms max=474.48ms count=7
E/flutter ( 7297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: plugins.flutter.io/webview
E/flutter ( 7297): at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:506)
E/flutter ( 7297): at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:193)
E/flutter ( 7297): at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:128)
E/flutter ( 7297): at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
E/flutter ( 7297): at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/flutter ( 7297): at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter ( 7297): at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter ( 7297): at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 7297): at android.os.Handler.handleCallback(Handler.java:958)
E/flutter ( 7297): at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 7297): at android.os.Looper.loopOnce(Looper.java:205)
E/flutter ( 7297): at android.os.Looper.loop(Looper.java:294)
E/flutter ( 7297): at android.app.ActivityThread.main(ActivityThread.java:8177)
E/flutter ( 7297): at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 7297): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/flutter ( 7297): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/flutter ( 7297): , null, null)
E/flutter ( 7297): #0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
E/flutter ( 7297): https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/pull/1 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:322:18)
E/flutter ( 7297):
E/flutter ( 7297): https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/pull/2 SurfaceAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1017:30)
E/flutter ( 7297):
E/flutter ( 7297): https://github.com/shinonome-inc/mobile_Mio_azuma_basic_flutter/pull/3 AndroidViewController.create (package:flutter/src/services/platform_views.dart:804:5)
E/flutter ( 7297):
E/flutter ( 7297):
```
